### PR TITLE
AI takes shortest path to victory and always finishes the game

### PR DESCRIPTION
**Pull request by Porem5002**
Hello again, I have made a few changes! These changes make the AI take the shortest path to victory by making it aware of how many turns it takes for it to win and based on this, the path that takes the least amount of turns to win is chosen.

Another thing that I changed was making the AI play in the first empty spot it finds in case a defeat is inevitable, effectivly solving #3. I don't know if this last change is the way you wanted, but reflecting on it a bit more it isn't that crucial really. So if you like it, cool, but if you don't, I can remove it if you want.

To finalize, I tested it and everything seems to be working as expected but if you find a problem tell me.

### CODE REVIEW

**Comment by rexim** [comment]
Why are you stealing my content? I wanted to stream that. :(

**Comment by Porem5002** [comment]
My apologies. Maybe you could focus on starting to expand the board to more than 3x3 or optimizing the algorithm like you mentioned on the other TODO.

And I am sure that you are not that mad, but I just wanted to contribute to the project on a meaningful way.

**Comment by rexim** [comment]
@Porem5002 fiiiiine! Thanks for the contribution! :)

**Comment by rexim** [comment]
@Porem5002 I actually like who you utilized the `giveup` variable. Since AI giving up earlier is not a problem anymore I wanted to remove it, but then I realized that I end up having a logical variable anyway. :D

**Comment by Porem5002** [comment]
@rexim Thank you, for your kind words my friend! :)

One more thing that I remembered and that I think is important to mention.
When the board is in this state:


If you active the AIs the result is this:


The reason why this happens is because if O blocked the top line, then X would play in the middle enabling him to make a line in two different ways, which would make him win anyway in the next move. So O realises he has no way of winning and will play on an empty spot.
I am mentioning this so you understand exactly why this happens if you aren't yet aware of it, because at least for me this was not very obvious at first glance and I decided not to change this since the AI already came to this conclusion before I made my changes.

**Pull request merged**
